#
# Combined Kubernetes file for deploying CRDP across a multi-node, multi-pod environment
#
# SECTION:  Pod Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: crdp
  name: crdp-deployment
spec:
  template:
     metadata:
        name: crdp
        labels:
          run: crdp
     spec:
      containers:
        - image: thalesciphertrust/ciphertrust-restful-data-protection:latest
          imagePullPolicy: IfNotPresent
          name: crdp-image
          env:
            - name: KEY_MANAGER_HOST
              value: "192.168.1.190"
            - name: SERVER_MODE
              value: "no-tls"
            - name: REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: crdp-secret-name
                  key: regtoken
          ports:
            - containerPort: 8090
  replicas: 6
  selector:
      matchLabels:
        run: crdp

---
#
# SECTION:  Service Deployment
#
apiVersion: v1
kind: Service
metadata:
  labels:
    run: crdp
  name: crdp-service
spec:
  selector:
    run: crdp
  type: NodePort
  ports:
    - port: 8090
      nodePort: 32085

---
#
# SECTION:  Ingress Deployment
# This will leverage the load balancer crdp.test256.io to route traffic to the appropriate node and pod.  
# Note that the load balancer is configured to route traffic to both nodes, so either node can be used 
# as the ingress point.  The ingress controller will then route traffic to the appropriate pod based 
# on the rules defined in the ingress resource.
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crdp-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4096M # reqd to accept large payloads
spec:
  ingressClassName: nginx
  rules:
  - host: crdp.test256.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: crdp-service
            port:
              number: 8090
